"""
Query Builder.

Takes a list of user-defined topics and survey terms from AppConfig and
produces a flat list of (topic, query_string) pairs.

Two pre-retrieval reductions happen here before any API call is made:

  1. Topic deduplication  — near-identical topics (fuzzy similarity ≥ 90)
     are merged into the shorter, more canonical form.  This avoids sending
     duplicate query sets for topics like:
       "AI for computer science education"
       "artificial intelligence in computer science education"

  2. Query-string deduplication — exact duplicate query strings (after topic
     merging) are collapsed so the same string is never sent twice.

When an Anthropic API key is provided, query strings are generated by an LLM
(claude-haiku) rather than a mechanical topic × survey_term cross-product.
LLM-generated queries use diverse phrasings, domain synonyms, and subtopics
that a keyword cross-product would never produce — significantly improving
recall for niche or multi-word topics.

Fallback: if no API key is set (or LLM call fails), the mechanical
cross-product is used transparently.
"""

from __future__ import annotations

import json
import logging
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path

import anthropic
from rapidfuzz import fuzz

from .config import AppConfig

# Cache for LLM-generated query strings — avoids re-calling the API on every
# run for the same topics.  Stored separately from the retrieval cache because
# queries are stable across many runs (30-day TTL vs 7-day for results).
_LLM_QUERY_CACHE_PATH = Path("data/raw/llm_query_cache.json")
_LLM_QUERY_CACHE_TTL_DAYS = 30

logger = logging.getLogger(__name__)

# Similarity threshold for merging topics (0–100).
# 90 catches paraphrases while keeping genuinely distinct topics apart.
TOPIC_SIMILARITY_THRESHOLD = 90

# Number of query strings the LLM generates per topic.
_LLM_QUERIES_PER_TOPIC = 10

# Common AI/ML abbreviations expanded before comparison so that
# "AI for education" and "artificial intelligence for education" merge correctly.
_ABBREVIATIONS: dict[str, str] = {
    r"\bai\b": "artificial intelligence",
    r"\bml\b": "machine learning",
    r"\bllm\b": "large language model",
    r"\bllms\b": "large language models",
    r"\bnlp\b": "natural language processing",
    r"\bcv\b": "computer vision",
    r"\bdl\b": "deep learning",
    r"\brl\b": "reinforcement learning",
    r"\brag\b": "retrieval augmented generation",
    r"\bgnn\b": "graph neural network",
    r"\bgnns\b": "graph neural networks",
}

_LLM_SYSTEM_PROMPT = (
    "You are an expert academic search query generator specialising in finding "
    "survey and review papers on AI/ML topics. "
    "Return ONLY a JSON array of strings. No explanation, no prose, no markdown."
)


@dataclass
class SearchQuery:
    """One concrete query to be sent to a retriever."""
    topic: str           # The canonical user-facing topic label
    query_string: str    # The exact query text sent to the API
    merged_topics: list[str] = field(default_factory=list)
    # ^ other topic labels that were folded into this one


def build_queries(cfg: AppConfig, use_llm: bool = True) -> list[SearchQuery]:
    """
    Generate search queries from config, with pre-retrieval deduplication.

    When `use_llm=True` and an Anthropic API key is present, each canonical
    topic gets LLM-generated query strings instead of a mechanical cross-product.
    Falls back to the cross-product silently if the API key is missing or the
    LLM call fails.

    Steps:
      1. Deduplicate near-identical topics.
      2. Generate query strings (LLM or cross-product).
      3. Drop global duplicate query strings.
    """
    canonical_topics = _deduplicate_topics(cfg.topics)

    if use_llm and cfg.anthropic_api_key:
        client = anthropic.Anthropic(api_key=cfg.anthropic_api_key)
        queries = _llm_query_set(canonical_topics, client)
        logger.info(
            "Query builder (LLM): %d topics → %d canonical → %d queries",
            len(cfg.topics), len(canonical_topics), len(queries),
        )
    else:
        queries = _cross_product(canonical_topics, cfg.survey_terms)
        original_count = len(cfg.topics) * len(cfg.survey_terms)
        logger.info(
            "Query builder (cross-product): %d topics → %d canonical × %d terms "
            "= %d queries (saved %d vs no dedup)",
            len(cfg.topics), len(canonical_topics), len(cfg.survey_terms),
            len(queries), original_count - len(queries),
        )

    return queries


# ─────────────────────────────────────────────────────────────────────────────
# LLM query generation
# ─────────────────────────────────────────────────────────────────────────────

def _llm_query_set(
    canonical_topics: list[dict],
    client: anthropic.Anthropic,
) -> list[SearchQuery]:
    """
    Generate query strings for all topics using the LLM in parallel, then
    deduplicate globally across topics.

    Each topic is dispatched concurrently so N topics take ~1 round-trip
    instead of N sequential round-trips.
    """
    cache = _load_llm_query_cache()
    queries: list[SearchQuery] = []
    seen: set[str] = set()

    # Fetch from cache or schedule an API call for each topic
    topics_needing_llm = []
    cached_results: dict[str, list[str]] = {}

    for group in canonical_topics:
        label = group["label"]
        cached = _llm_cache_get(cache, label)
        if cached is not None:
            logger.info("LLM query cache hit for topic '%s'", label)
            cached_results[label] = cached
        else:
            topics_needing_llm.append(group)

    # Parallel API calls for cache-missed topics
    if topics_needing_llm:
        with ThreadPoolExecutor(max_workers=min(len(topics_needing_llm), 5)) as ex:
            future_to_group = {
                ex.submit(_llm_queries_for_topic, client, g["label"]): g
                for g in topics_needing_llm
            }
            for future in as_completed(future_to_group):
                group = future_to_group[future]
                label = group["label"]
                try:
                    strings = future.result()
                except Exception as exc:
                    logger.warning("LLM query generation failed for '%s': %s", label, exc)
                    strings = _fallback_queries(label)
                cached_results[label] = strings
                _llm_cache_set(cache, label, strings)

        _save_llm_query_cache(cache)

    # Assemble SearchQuery objects in canonical topic order
    for group in canonical_topics:
        label = group["label"]
        aliases = group["aliases"]
        for q_str in cached_results.get(label, []):
            q_str = q_str.strip()
            if not q_str or q_str in seen:
                continue
            seen.add(q_str)
            queries.append(SearchQuery(
                topic=label,
                query_string=q_str,
                merged_topics=aliases,
            ))

    return queries


def _llm_queries_for_topic(
    client: anthropic.Anthropic,
    topic: str,
    n: int = _LLM_QUERIES_PER_TOPIC,
) -> list[str]:
    """
    Ask claude-haiku to generate `n` search query strings for `topic`, then
    validate them to remove any that have drifted to adjacent or broader topics.

    Falls back to the mechanical cross-product strings on any error so callers
    never get an empty list.
    """
    prompt = (
        f"Generate {n} diverse academic search queries to find SURVEY papers, "
        f"literature reviews, and systematic reviews about this EXACT topic:\n\n"
        f"  \"{topic}\"\n\n"
        f"Rules:\n"
        f"- Every query must stay on THIS EXACT TOPIC — do not drift to broader, "
        f"narrower, or adjacent topics.\n"
        f"- Vary only the phrasing and terminology, never the core subject.\n"
        f"- Each query MUST include at least one survey/review term "
        f"(survey, review, overview, taxonomy, literature review, systematic review, "
        f"state of the art, etc.).\n"
        f"- Queries should work on academic APIs (OpenAlex, arXiv, CORE): "
        f"3–8 natural English words.\n"
        f"- No duplicate queries.\n\n"
        f"Return a JSON array of exactly {n} query strings."
    )

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=_LLM_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = response.content[0].text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        raw = raw.strip()

        result = json.loads(raw)
        if isinstance(result, list) and result:
            strings = [str(s).strip() for s in result if str(s).strip()]

            # Validate: remove queries that drifted from the intended topic
            strings = _validate_queries(client, topic, strings)

            logger.info(
                "LLM generated %d queries for topic '%s':", len(strings), topic
            )
            for q in strings:
                logger.info("  • %s", q)
            return strings

        logger.warning("LLM returned empty/invalid list for topic '%s'", topic)

    except Exception as exc:
        logger.warning(
            "LLM query generation failed for topic '%s': %s — falling back",
            topic, exc,
        )

    return _fallback_queries(topic)


def _validate_queries(
    client: anthropic.Anthropic,
    topic: str,
    queries: list[str],
) -> list[str]:
    """
    Filter generated queries to remove any that have drifted from the topic.

    Asks the same claude-haiku model to check each query: does it specifically
    search for surveys about the EXACT topic, or has it wandered to something
    adjacent?  Queries that fail the check are dropped.

    We always keep at least 5 queries (falls back to the full list if too many
    are rejected) so retrieval never runs with an empty query set.
    """
    if len(queries) <= 3:
        return queries  # not worth a validation call for tiny sets

    numbered = "\n".join(f"{i+1}. {q}" for i, q in enumerate(queries))
    prompt = (
        f"Research topic: \"{topic}\"\n\n"
        f"Below are search queries generated to find survey papers about that topic. "
        f"For each query, answer true if it specifically searches for surveys/reviews "
        f"about the EXACT topic above, or false if it has drifted to a different, "
        f"broader, or adjacent topic.\n\n"
        f"{numbered}\n\n"
        f"Return a JSON array of {len(queries)} booleans in the same order. "
        f"No explanation."
    )

    try:
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=128,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = resp.content[0].text.strip()
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
        mask = json.loads(raw.strip())

        if isinstance(mask, list) and len(mask) == len(queries):
            validated = [q for q, keep in zip(queries, mask) if keep]
            removed = [q for q, keep in zip(queries, mask) if not keep]
            if removed:
                logger.info(
                    "Query validation removed %d drifted queries for '%s': %s",
                    len(removed), topic,
                    "; ".join(f'"{q}"' for q in removed),
                )
            # Safety floor: always keep at least 5 queries
            if len(validated) >= 5:
                return validated
            logger.debug(
                "Validation kept only %d queries — reverting to full set", len(validated)
            )
    except Exception as exc:
        logger.debug("Query validation failed for '%s': %s — keeping all", topic, exc)

    return queries


def _fallback_queries(topic: str) -> list[str]:
    return [
        f"{topic} survey",
        f"{topic} review",
        f"{topic} systematic review",
        f"{topic} literature review",
        f"{topic} overview",
    ]


# ─────────────────────────────────────────────────────────────────────────────
# LLM query string cache
# ─────────────────────────────────────────────────────────────────────────────

def _load_llm_query_cache() -> dict:
    """Load the on-disk LLM query cache, evicting entries older than TTL."""
    if not _LLM_QUERY_CACHE_PATH.exists():
        return {}
    try:
        with _LLM_QUERY_CACHE_PATH.open(encoding="utf-8") as f:
            raw: dict = json.load(f)
        cutoff = datetime.utcnow() - timedelta(days=_LLM_QUERY_CACHE_TTL_DAYS)
        return {
            k: v for k, v in raw.items()
            if datetime.fromisoformat(v.get("generated_at", "2000-01-01")) > cutoff
        }
    except Exception as exc:
        logger.warning("LLM query cache unreadable — starting fresh: %s", exc)
        return {}


def _save_llm_query_cache(cache: dict) -> None:
    _LLM_QUERY_CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with _LLM_QUERY_CACHE_PATH.open("w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)


def _llm_cache_get(cache: dict, topic: str) -> list[str] | None:
    entry = cache.get(topic)
    return entry["queries"] if entry else None


def _llm_cache_set(cache: dict, topic: str, queries: list[str]) -> None:
    cache[topic] = {
        "queries": queries,
        "generated_at": datetime.utcnow().isoformat(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Topic deduplication
# ─────────────────────────────────────────────────────────────────────────────

def _deduplicate_topics(topics: list[str]) -> list[dict]:
    """
    Merge near-duplicate topics using fuzzy string similarity.

    Returns a list of dicts:
      {"label": <canonical label>, "aliases": [<other merged labels>]}

    The canonical label is the shortest of the merged group (shorter labels
    tend to be the cleaner form, e.g. "AI safety" vs "artificial intelligence
    safety and alignment").
    """
    groups: list[dict] = []  # [{"label": str, "aliases": [str]}]

    for topic in topics:
        matched_idx = _find_similar_group(topic, groups)
        if matched_idx is not None:
            g = groups[matched_idx]
            g["aliases"].append(topic)
            # Keep the LONGER label as canonical — longer phrases are more
            # specific and produce better results on academic search APIs
            # (e.g. "large language models" outperforms "LLMs" as a query).
            if len(topic) > len(g["label"]):
                g["aliases"].append(g["label"])
                g["aliases"].remove(topic)
                g["label"] = topic
            logger.info(
                "Topic dedup: merged '%s' → '%s'", topic, g["label"]
            )
        else:
            groups.append({"label": topic, "aliases": []})

    return groups


def _find_similar_group(topic: str, groups: list[dict]) -> int | None:
    """Return the index of the first group whose label is similar enough.

    Comparison is done on abbreviation-expanded, lowercased text so that
    'AI for education' and 'artificial intelligence for education' match.
    """
    expanded_topic = _expand_abbreviations(topic)
    for idx, g in enumerate(groups):
        expanded_label = _expand_abbreviations(g["label"])
        score = fuzz.token_sort_ratio(expanded_topic, expanded_label)
        if score >= TOPIC_SIMILARITY_THRESHOLD:
            return idx
    return None


def _expand_abbreviations(text: str) -> str:
    """Replace known abbreviations with their full forms for comparison."""
    result = text.lower()
    for pattern, expansion in _ABBREVIATIONS.items():
        result = re.sub(pattern, expansion, result)
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Query cross-product
# ─────────────────────────────────────────────────────────────────────────────

def _cross_product(
    canonical_topics: list[dict],
    survey_terms: list[str],
) -> list[SearchQuery]:
    """
    Build one SearchQuery per (canonical_topic × survey_term), deduplicating
    query strings globally.
    """
    queries: list[SearchQuery] = []
    seen_strings: set[str] = set()

    for group in canonical_topics:
        label = group["label"]
        aliases = group["aliases"]

        for term in survey_terms:
            q_str = f'"{label}" "{term}"'
            if q_str in seen_strings:
                continue
            seen_strings.add(q_str)
            queries.append(SearchQuery(
                topic=label,
                query_string=q_str,
                merged_topics=aliases,
            ))

    return queries
